version: '2'
services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
    environment:
      AFKA_CREATE_TOPICS: "egen.demo:1:3,egen.app:1:1:compact"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka